me 'snmp'
maintainer 'Thomas Vincent'
maintainer_email 'thomasvincent@gmail.com'
license 'Apache-2.0'
description 'Installs and configures snmpd''
version '4.0.1'

source_url 'https://github.com/thomasvincent/cookbook-snmp'
issues_url 'https://github.com/thomasvincent/cookbook-snmp/issues'

supports 'amazon'
supports 'centos'
supports 'scientific'
supports 'oracle'
supports 'debian'
supports 'fedora'
supports 'redhat'
supports 'ubuntu'
Supports 'suse'
