name 'snmp'
maintainer 'Thomas Vincent'
maintainer_email 'thomasvincent@gmail.com'
license 'Apache-2.0'
version '5.0.1'
description 'Installs and configures snmpd'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url 'https://github.com/thomasvincent/cookbook-snmp'
issues_url 'https://github.com/thomasvincent/cookbook-snmp/issues'

supports 'amazon'
supports 'centos'
supports 'scientific'
supports 'oracle'
supports 'debian'
supports 'fedora'
supports 'redhat'
supports 'ubuntu'
supports 'suse'
